version: '3'

services:
  arm64v8-ubuntu:
    image: arm64v8/ubuntu:latest
    command: /bin/bash
    privileged: true
    restart: always
    volumes:
      - /home/liuchao/docker/workspace:/home/repo
    ports:
      - "8080:80"
    environment:
      - TZ=Asia/Shanghai